jobs:
  main:
    image: node:6
    steps:
      - init: npm install
      - test: npm test
      - pack: npm pack
      - mv: mv screwdriver-sd-test-0.0.1.tgz $SD_ARTIFACTS_DIR
      - set: meta set foo bar
      - get: meta get foo
